# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Methods
  items:
    - label: 'User'
      link: '/methods/user'
    - label: 'Servers'
      link: '/methods/servers'
    - label: 'Services'
      link: '/methods/services'
    - label: 'Daemons'
      link: '/methods/daemons'
    - label: 'Firewall Rules'
      link: '/methods/firewall-rules'
    - label: 'Scheduled Jobs'
      link: '/methods/scheduled-jobs'
    - label: 'PHP'
      link: '/methods/php'
    - label: 'Databases'
      link: '/methods/databases'
    - label: 'Database Users'
      link: '/methods/database-users'
    - label: 'Nginx Templates'
      link: '/methods/nginx-templates'
    - label: 'Sites'
      link: '/methods/sites'
    - label: 'SSL Certificates'
      link: '/methods/ssl-certificates'
    - label: 'SSH Keys'
      link: '/methods/ssh-keys'
    - label: 'Workers'
      link: '/methods/workers'
    - label: 'Redirect Rules'
      link: '/methods/redirect-rules'
    - label: 'Security Rules'
      link: '/methods/security-rules'
    - label: 'Deployment'
      link: '/methods/deployment'
    - label: 'Deployment History'
      link: '/methods/deployment-history'
    - label: 'Configuration Files'
      link: '/methods/configuration-files'
    - label: 'git Projects'
      link: '/methods/git-projects'
    - label: 'WordPress'
      link: '/methods/wordpress'
    - label: 'phpMyAdmin'
      link: '/methods/phpmyadmin'
    - label: 'Webhooks'
      link: '/methods/webhooks'
    - label: 'Recipes'
      link: '/methods/recipes'
    - label: 'Regions'
      link: '/methods/regions'
    - label: 'Credentials'
      link: '/methods/credentials'
    - label: 'Backups'
      link: '/methods/backups'
    - label: 'Monitoring'
      link: '/methods/monitoring'
    - label: 'Server Logs'
      link: '/methods/server-logs'
- label: More
  items:
    - label: 'Github'
      link: https://github.com/GeoffSelby/laravel-forge-javascript-sdk
